.TH bambam 6 "12 February 2014" "version 0.5"
.SH NAME
bambam \- a keyboard mashing and doodling game for babies
.SH SYNOPSIS
.B bambam
[\fIOPTIONS\fR]
.SH DESCRIPTION
.TP
\fB\-u\fR, \fB\-\-uppercase\fR
Whether to show UPPER-CASE letters.
.TP
\fB\-d\fR, \fB\-\-deterministic\-sounds\fR
Whether to produce same sounds on same key presses.
.TP
\fB\-\-sound_blacklist\fR=\fIGLOB\fR
List sound filename patterns to never play.
.PP
bambam is a keyboard and mouse game for babies written in Python.
Pressing letter keys prints them in random locations and colours.
Pressing any other key draws little pictures in random locations.
Dragging the mouse while the mouse button is pressed draws in randomly changing
colours.
The screen is cleared at random.
.SH NOTES
\fBTo quit, type quit in the game\fR.
To turn the sound off and on, type mute and unmute, respectively, in the game.
.SH AUTHOR
Spike Burch <spikeb@gmail.com>
.BR
Marcin Owsiany <marcin@owsiany.pl>

