.TH bambam 6 "10 September 2022" "version 1.2.0"
.SH NAME
bambam \- a keyboard mashing and doodling game for babies and toddlers
.SH SYNOPSIS
.B bambam
[\fIOPTIONS\fR]
.SH DESCRIPTION
.TP
\fB\-u\fR, \fB\-\-uppercase\fR
Show UPPER-CASE letters.
.TP
\fB\-d\fR, \fB\-\-deterministic\-sounds\fR
Produce same sounds on same key presses.
.TP
\fB\-D\fR, \fB\-\-dark\fR
Use a dark background instead of a light one.
.TP
\fB\-m\fR, \fB\-\-mute\fR
Do not play any sounds.
.TP
\fB\-\-sound_blacklist\fR=\fIGLOB\fR
List of sound filename patterns to never play.
.TP
\fB\-\-image_blacklist\fR=\fIGLOB\fR
List of image filename patterns to never show.
.TP
\fB\-\-wayland\-ok\fR
Do not prevent running under Wayland. See the \fBNOTES\fR section.
.PP
bambam is a keyboard and mouse game for babies written in Python.
Pressing letter keys prints them in random locations and colours.
Pressing any other key draws little pictures in random locations.
Dragging the mouse while the mouse button is pressed draws in randomly changing
colours.
The screen is cleared at random.
.SH NOTES
.B
To quit, directly type the command mentioned in the upper left-hand corner of the window. In the English locales, this is the word: quit.
.PP
\fBBe aware\fR that there are ways to switch to another application from bambam:
.IP \(bu
when running under Wayland, it is not currently possible for bambam to grab all
key presses.
A consequence of that is that if you use GNOME Shell, pressing the Windows
(a.k.a. Super) key will activate the activities overview.
Please check your environment.
As a workaround, starting with version 1.1.2, bambam will try to detect if it
is running under Wayland. If this is the case, bambam will display a warning
and refuse to work.
You can disable this workaround, with the \fB\-\-wayland\-ok\fR option.
.IP \(bu
bambam does not block virtual terminal switching (e.g.
CTRL+ALT+F1). See the example 50-dont-vt-switch.conf file if you would like to
block that.
.IP \(bu
there may be other yet unknown ways in other environments and window managers.
.PP
For the above reasons, starting with version 1.2.0,
.B
it is possible and recommended to run bambam in a dedicated login session.
.IP \(bu
One way to do this is to select BamBam session type from your display manager
settings when logging in (look for a gear icon).
.IP \(bu
Another way is use command such as \fBexec startx bambam\fR from a text
console.
.PP
To turn the sound off and on, type mute and unmute, respectively, in the game.
.PP
bambam loads images (GIF, JPEG, PNG and TIFF files) and sounds (WAV and OGG
files) from the following directories:
.IP \(bu
the \fBdata\fR directory distributed with the game,
.IP \(bu
\fB$XDG_DATA_HOME\fR (usually ~/.local/share/bambam/data)
.PP
When scanning directories for files, bambam \fBdoes\fR follow symbolic links
and descend directories. This makes is easy to have bambam use files located
elsewhere.
.SH AUTHOR
Spike Burch <spikeb@gmail.com>
.BR
Marcin Owsiany <marcin@owsiany.pl>
